name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgmp-dev

    - uses: actions/checkout@v4

    - name: Cache OPAM
      uses: actions/cache@v4
      with:
        path: ~/.opam
        key: ${{ runner.os }}-opam-${{ hashFiles('**/_CoqProject') }}
        restore-keys: |
          ${{ runner.os }}-opam-

    - name: Set up OCaml and OPAM
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: '4.14.1'
        opam-repositories: |
          default: https://opam.ocaml.org
          coq-released: https://coq.inria.fr/opam/released

    - name: Create Clean OPAM Switch
      run: |
        SWITCH_NAME="collatz-proof"
        OCAML_VERSION="ocaml-base-compiler.4.14.1"

        echo "Creating OPAM switch '${SWITCH_NAME}'..."
        opam switch create "${SWITCH_NAME}" "${OCAML_VERSION}" || { echo "Switch creation failed"; exit 1; }
        echo "Activating environment..."
        eval $(opam env --switch="${SWITCH_NAME}" --set-switch)

        echo "Adding OPAM repository..."
        opam repository add coq-released https://coq.inria.fr/opam/released --all-switches
        opam update

    - name: Install Coq
      run: |
        echo "Installing Coq 8.16.1..."
        opam install coq.8.16.1 -y --verbose --debug || { echo "Coq installation failed"; exit 1; }
        echo "Activating environment..."
        eval $(opam env --switch=collatz-proof --set-switch)

    - name: Ensure Coq Paths Are Set
      run: |
        COQ_PATH=$(opam var coq:bin)
        echo "COQ_PATH is $COQ_PATH"
        echo "export PATH=$COQ_PATH:\$PATH" >> $GITHUB_ENV

    - name: Verify Coq Installation
      run: |
        echo "Checking Coq version..."
        eval $(opam env --switch=collatz-proof --set-switch)
        which coqtop || { echo "coqtop binary not found in PATH"; exit 1; }
        coqtop --version || { echo "coqtop execution failed