name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up OCaml and OPAM
      uses: ocaml/setup-ocaml@v3
      with:
        # Updated OCaml compiler version to 4.13.1 for Coq 8.14.1 compatibility
        ocaml-compiler: '4.13.1'
        opam-repositories: |
          default: https://opam.ocaml.org
          coq-released: https://coq.inria.fr/opam/released

    - name: Create OPAM Switch and Install Coq
      run: |
        SWITCH_NAME="collatz-proof"
        # Updated OCaml version for the switch to 4.13.1
        OCAML_VERSION_FOR_SWITCH="ocaml-base-compiler.4.13.1"

        echo "Creating OPAM switch '${SWITCH_NAME}' with OCaml ${OCAML_VERSION_FOR_SWITCH}..."
        opam switch create "${SWITCH_NAME}" "${OCAML_VERSION_FOR_SWITCH}"

        echo "Activating environment for switch '${SWITCH_NAME}'..."
        eval $(opam env --switch="${SWITCH_NAME}" --set-switch)

        echo "Installing Coq 8.14.1 in switch '${SWITCH_NAME}'..."
        opam install -y coq.8.14.1
        echo "Coq installation complete."

    - name: Compile Coq project
      run: |
        SWITCH_NAME="collatz-proof"

        echo "Activating environment for switch '${SWITCH_NAME}' for compilation..."
        eval $(opam env --switch="${SWITCH_NAME}" --set-switch)

        echo "Generating Makefile using coq_makefile..."
        coq_makefile -f _CoqProject -o Makefile

        echo "Compiling Coq project using make..."
        make
        echo "Compilation complete."