name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgmp-dev

    - uses: actions/checkout@v4

    - name: Cache OPAM
      uses: actions/cache@v4
      with:
        path: ~/.opam
        key: ${{ runner.os }}-opam-${{ hashFiles('**/_CoqProject') }}
        restore-keys: |
          ${{ runner.os }}-opam-

    - name: Set up OCaml and OPAM
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: '4.13.1'
        opam-repositories: |
          default: https://opam.ocaml.org
          coq-released: https://coq.inria.fr/opam/released

    - name: Create OPAM Switch and Install Coq
      run: |
        SWITCH_NAME="collatz-proof"
        OCAML_VERSION_FOR_SWITCH="ocaml-base-compiler.4.13.1"

        echo "Creating OPAM switch '${SWITCH_NAME}' with OCaml ${OCAML_VERSION_FOR_SWITCH}..."
        if ! opam switch list --short | grep -q "^${SWITCH_NAME}$"; then
          opam switch create "${SWITCH_NAME}" "${OCAML_VERSION_FOR_SWITCH}"
        else
          echo "Switch '${SWITCH_NAME}' already exists."
        fi

        echo "Activating environment for switch '${SWITCH_NAME}'..."
        eval $(opam env --switch="${SWITCH_NAME}" --set-switch)

        echo "Adding and updating OPAM repositories..."
        opam repository add coq-released https://coq.inria.fr/opam/released --all-switches
        opam update

        echo "Installing Coq 8.14.1 and Coq standard library..."
        for i in {1..3}; do
          opam install -y coq.8.14.1 coq-stdlib && break
          echo "Retry $i failed, trying again..."
          sleep 5
        done
        echo "Coq installation complete."

    - name: Debug OPAM and Coq Setup
      run: |
        opam switch list
        opam list --installed
        coqtop --version

    - name: Compile Coq project
      run: |
        SWITCH_NAME="collatz-proof"

        echo "Activating environment for switch '${SWITCH_NAME}'..."
        eval $(opam env --switch="${SWITCH_NAME}" --set-switch)

        echo "Generating Makefile using coq_makefile..."
        coq_makefile -f _CoqProject -o Makefile

        echo "Inspecting Makefile..."
        cat Makefile

        echo "Compiling Coq project using make..."
        make -j1 V=1
        echo "Compilation complete."