name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up OPAM
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.12.x
    - name: Install Coq
      run: opam install -y coq.8.14.1
    - name: Compile
      run: |
        eval $(opam env)
        coq_makefile -f _CoqProject -o Makefile
        make