name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up OPAM
        run: |
          sudo apt-get update
          sudo apt-get install -y opam
          opam init --disable-sandboxing --yes
          opam update
      - name: Install Coq
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam install -y coq.8.14.1
      - name: Compile Coq
        run: |
          eval $(opam env)
          coq_makefile -f _CoqProject -o Makefile
          make