name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up OPAM
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.12.1
        opam-repositories: |
          default: https://opam.ocaml.org
        opam-depext: false
    - name: Install Coq
      run: |
        eval $(opam env)
        opam update
        opam install -y coq.8.14.1
    - name: Debug Loadpath
      run: |
        eval $(opam env)
        coqc -where
        export COQPATH="$(coqc -where)/theories"
        echo "COQPATH: $COQPATH"
        ls -l "$(coqc -where)/theories"
        coqdep -R . CollatzProof collatz_base.v > deps.d
        cat deps.d
    - name: Compile
      run: |
        eval $(opam env)
        export COQPATH="$(coqc -where)/theories"
        coq_makefile -f _CoqProject -o Makefile
        make