name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up OCaml and OPAM
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 4.14.1
        opam-repositories: |
          default: https://opam.ocaml.org
          coq-released: https://coq.inria.fr/opam/released

    - name: Create OPAM Switch
      run: |
        opam switch create collatz-proof ocaml-base-compiler.4.14.1
        opam install -y coq.8.14.1
        eval $(opam env)

    - name: Compile Coq project
      run: |
        eval $(opam env)
        coq_makefile -f _CoqProject -o Makefile
        make
