name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgmp-dev

    - uses: actions/checkout@v4

    - name: Cache OPAM
      uses: actions/cache@v4
      with:
        path: ~/.opam
        key: ${{ runner.os }}-opam-${{ hashFiles('**/_CoqProject') }}-v3 # Incremented to v3 to invalidate cache
        restore-keys: |
          ${{ runner.os }}-opam-

    - name: Set up OCaml and OPAM
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: '4.14.1'
        opam-repositories: |
          default: https://opam.ocaml.org
          coq-released: https://coq.inria.fr/opam/released

    - name: Create Clean OPAM Switch
      run: |
        set -e
        SWITCH_NAME="collatz-proof"
        OCAML_VERSION="ocaml-base-compiler.4.14.1"

        echo "Removing existing switch if present..."
        opam switch remove "${SWITCH_NAME}" --yes || true

        echo "Creating OPAM switch '${SWITCH_NAME}' with OCAML ${OCAML_VERSION}..."
        opam switch create "${SWITCH_NAME}" "${OCAML_VERSION}"
        if [ $? -ne 0 ]; then
          echo "Switch creation failed"
          exit 1
        fi

        echo "Activating environment..."
        eval $(opam env --switch="${SWITCH_NAME}" --set-switch)

        echo "Adding OPAM repository..."
        opam repository add coq-released https://coq.inria.fr/opam/released --all-switches
        if [ $? -ne 0 ]; then
          echo "Repository add failed"
          exit 1
        fi

        echo "Updating OPAM..."
        opam update
        if [ $? -ne 0 ]; then
          echo "OPAM update failed"
          exit 1
        fi

        echo "Checking OPAM configuration..."
        opam config report > opam_config.log
        cat opam_config.log
        echo "Listing available Coq versions..."
        opam list --all-versions coq > coq_versions.log
        cat coq_versions.log
        echo "Listing repository state..."
        opam repo list > repo_list.log
        cat repo_list.log

    - name: Pin Coq Version (Alternative 2 - Git Pinning)
      run: |
        set -e
        echo "Pinning Coq 8.16.1 from Git..."
        opam pin add coq 8.16.1 https://github.com/coq/coq.git#V8.16.1 -y --verbose --debug > pin_coq.log 2>&1
        if [ $? -ne 0 ]; then
          echo "Pinning failed"
          cat pin_coq.log
          opam list --all-versions coq
          exit 1
        fi
        cat pin_coq.log
        echo "Updating environment..."
        eval $(opam env --switch=collatz-proof --set-switch)
        echo "Checking PATH..."
        echo $PATH
        echo "Verifying OPAM environment..."
        opam env

    - name: Install Coq (Alternative 2 - Git Pinning)
      run: |
        set -e
        echo "Installing Coq 8.16.1 (Git Pinning)..."
        opam install coq.8.16.1 -y --verbose --debug > install_coq.log 2>&1
        if [ $? -ne 0 ]; then
          echo "Coq 8.16.1 installation failed"
          cat install_coq.log
          opam list --all-versions coq
          exit 1
        fi
        cat install_coq.log
        echo "Updating environment..."
        eval $(opam env --switch=collatz-proof --set-switch)
        echo "Checking PATH..."
        echo $PATH
        echo "Checking coqtop location..."
        which coqtop || { echo "coqtop not found in PATH"; exit 1; }
        echo "Verifying OPAM environment..."
        opam env

    # Alternative 1: Simplified Pinning with coq-released Repository
    # - Uses opam pin add coq 8.16.1 without Git URL, relying on coq-released repository
    # - To use, comment out Alternative 2 and 3 sections, and uncomment this section
    # - name: Pin Coq Version (Alternative 1 - Simplified Pinning)
    #   run: |
    #     set -e
    #     echo "Pinning Coq 8.16.1 (Simplified Pinning)..."
    #     opam pin add coq 8.16.1 -y --verbose --debug > pin_coq.log 2>&1
    #     if [ $? -ne 0 ]; then
    #       echo "Pinning failed"
    #       cat pin_coq.log
    #       opam list --all-versions coq
    #       exit 1
    #     fi
    #     cat pin_coq.log
    #     echo "Updating environment..."
    #     eval $(opam env --switch=collatz-proof --set-switch)
    #     echo "Checking PATH..."
    #     echo $PATH
    #     echo "Verifying OPAM environment..."
    #     opam env
    #
    # - name: Install Coq (Alternative 1 - Simplified Pinning)
    #   run: |
    #     set -e
    #     echo "Installing Coq 8.16.1 (Simplified Pinning)..."
    #     opam install coq.8.16.1 -y --verbose --debug > install_coq.log 2>&1
    #     if [ $? -ne 0 ]; then
    #       echo "Coq 8.16.1 installation failed"
    #       cat install_coq.log
    #       opam list --all-versions coq
    #       exit 1
    #     fi
    #     cat install_coq.log
    #     echo "Updating environment..."
    #     eval $(opam env --switch=collatz-proof --set-switch)
    #     echo "Checking PATH..."
    #     echo $PATH
    #     echo "Checking coqtop location..."
    #     which coqtop || { echo "coqtop not found in PATH"; exit 1; }
    #     echo "Verifying OPAM environment..."
    #     opam env

    # Alternative 3: Rocq-Based Setup
    # - Uses coq.9.0.0 to align with rocq-core.9.0.0 packages
    # - Requires updating Coq files to use Corelib.* imports (e.g., Corelib.Init.Datatypes)
    # - To use, comment out Alternative 1 and 2 sections, and uncomment this section
    # - name: Pin Rocq Version (Alternative 3 - Rocq Setup)
    #   run: |
    #     set -e
    #     echo "Pinning Rocq 9.0.0..."
    #     opam pin add coq 9.0.0 -y --verbose --debug > pin_coq.log 2>&1
    #     if [ $? -ne 0 ]; then
    #       echo "Pinning failed"
    #       cat pin_coq.log
    #       opam list --all-versions coq
    #       exit 1
    #     fi
    #     cat pin_coq.log
    #     echo "Updating environment..."
    #     eval $(opam env --switch=collatz-proof --set-switch)
    #     echo "Checking PATH..."
    #     echo $PATH
    #     echo "Verifying OPAM environment..."
    #     opam env
    #
    # - name: Install Rocq (Alternative 3 - Rocq Setup)
    #   run: |
    #     set -e
    #     echo "Installing Rocq 9.0.0..."
    #     opam install coq.9.0.0 -y --verbose --debug > install_coq.log 2>&1
    #     if [ $? -ne 0 ]; then
    #       echo "Rocq 9.0.0 installation failed"
    #       cat install_coq.log
    #       opam list --all-versions coq
    #       exit 1
    #     fi
    #     cat install_coq.log
    #     echo "Updating environment..."
    #     eval $(opam env --switch=collatz-proof --set-switch)
    #     echo "Checking PATH..."
    #     echo $PATH
    #     echo "Checking coqtop location..."
    #     which coqtop || { echo "coqtop not found in PATH"; exit 1; }
    #     echo "Verifying OPAM environment..."
    #     opam env

    - name: Verify Coq Installation
      run: |
        set -e
        echo "Checking Coq version..."
        eval $(opam env --switch=collatz-proof --set-switch)
        coqtop --version > coq_version.log 2>&1
        if [ $? -ne 0 ]; then
          echo "coqtop binary not found in PATH"
          cat coq_version.log
          exit 1
        fi
        cat coq_version.log
        echo "Listing installed packages..."
        opam list --installed > installed_packages.log
        cat installed_packages.log
        # Check for expected Coq version (8.16.1 for Alternatives 1 and 2, 9.0.0 for Alternative 3)
        EXPECTED_VERSION=$(grep "coq.*\(8.16.1\|9.0.0\)" installed_packages.log || echo "")
        if [ -z "$EXPECTED_VERSION" ]; then
          echo "Expected Coq version (8.16.1 or 9.0.0) not found in installed packages"
          opam list --all-versions coq
          exit 1
        fi
        echo "Coq installation verified."

    - name: Install Dependencies
      run: |
        set -e
        echo "Installing coq-elpi..."
        eval $(opam env --switch=collatz-proof --set-switch)
        opam install -y --verbose --debug coq-elpi.2.5.2 > install_elpi.log 2>&1
        if [ $? -ne 0 ]; then
          echo "coq-elpi installation failed"
          cat install_elpi.log
          exit 1
        fi
        cat install_elpi.log
        echo "Installing coq-mathcomp-ssreflect..."
        opam install -y --verbose --debug coq-mathcomp-ssreflect.2.4.0 > install_mathcomp.log 2>&1
        if [ $? -ne 0 ]; then
          echo "coq-mathcomp-ssreflect installation failed"
          cat install_mathcomp.log
          exit 1
        fi
        cat install_mathcomp.log
        echo "Updating environment..."
        eval $(opam env --switch=collatz-proof --set-switch)

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: opam-logs
        path: |
          *.log
        retention-days: 7

    - name: Compile Coq Project
      run: |
        set -e
        echo "Activating environment..."
        eval $(opam env --switch=collatz-proof --set-switch)
        echo "Verifying OPAM environment..."
        opam env
        echo "Generating Makefile..."
        coq_makefile -f _CoqProject -o Makefile -W "-elpi.linear-variable,-elpi.missing-types"
        if [ $? -ne 0 ]; then
          echo "coq_makefile failed"
          exit 1
        fi
        echo "Inspecting Makefile..."
        cat Makefile
        echo "Compiling Coq project..."
        make -j1 V=1
        if [ $? -ne 0 ]; then
          echo "Compilation failed, showing errors:"
          cat *.v.err || true
          exit 1
        fi
        echo "Compilation complete."
```