name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgmp-dev

    - uses: actions/checkout@v4

    - name: Cache OPAM
      uses: actions/cache@v4
      with:
        path: ~/.opam
        key: ${{ runner.os }}-opam-${{ hashFiles(\'**/_CoqProject\') }}
        restore-keys: |
          ${{ runner.os }}-opam-

    - name: Set up OCaml and OPAM
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: \'4.14.1\'
        opam-repositories: |
          default: https://opam.ocaml.org
          coq-released: https://coq.inria.fr/opam/released

    - name: Create Clean OPAM Switch
      run: |
        SWITCH_NAME=\
