name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgmp-dev

    - uses: actions/checkout@v4

    - name: Cache OPAM
      uses: actions/cache@v4
      with:
        path: ~/.opam
        key: ${{ runner.os }}-opam-${{ hashFiles('**/_CoqProject') }}
        restore-keys: |
          ${{ runner.os }}-opam-

    - name: Set up OCaml and OPAM
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: '4.14.1'
        opam-repositories: |
          default: https://opam.ocaml.org
          coq-released: https://coq.inria.fr/opam/released

    - name: Create OPAM Switch and Install Coq
      run: |
        SWITCH_NAME="collatz-proof"
        OCAML_VERSION_FOR_SWITCH="ocaml-base-compiler.4.14.1"

        echo "Creating OPAM switch '${SWITCH_NAME}' with OCaml ${OCAML_VERSION_FOR_SWITCH}..."
        if ! opam switch list --short | grep -q "^${SWITCH_NAME}$"; then
          opam switch create "${SWITCH_NAME}" "${OCAML_VERSION_FOR_SWITCH}" || { echo "Switch creation failed"; exit 1; }
        else
          echo "Switch '${SWITCH_NAME}' already exists."
        fi

        echo "Activating environment for switch '${SWITCH_NAME}'..."
        eval $(opam env --switch="${SWITCH_NAME}" --set-switch)

        echo "Adding and updating OPAM repositories..."
        opam repository add coq-released https://coq.inria.fr/opam/released --all-switches || { echo "Repository add failed"; exit 1; }
        opam update || { echo "OPAM update failed"; exit 1; }

        echo "Pinning and installing Coq 8.16.1..."
        opam pin add coq 8.16.1 -y --verbose || { echo "Coq 8.16.1 pinning/installation failed"; opam list --all-versions coq; exit 1; }

        echo "Installing coq-elpi..."
        opam install -y --verbose coq-elpi.2.5.2 || { echo "coq-elpi installation failed"; exit 1; }

        echo "Installing coq-mathcomp-ssreflect..."
        opam install -y --verbose coq-mathcomp-ssreflect.2.4.0 || { echo "coq-mathcomp-ssreflect installation failed"; exit 1; }

        echo "Verifying Coq installation..."
        if ! opam list --installed | grep -q "coq.*8.16.1"; then
          echo "Coq 8.16.1 not found in installed packages"
          opam list --all-versions coq
          exit 1
        fi
        echo "Coq installation complete."

    - name: Debug OPAM and Coq Setup
      run: |
        echo "Listing OPAM switches..."
        opam switch list
        echo "Listing installed packages..."
        opam list --installed
        echo "Checking Coq version..."
        coqtop --version || { echo "coqtop not found"; exit 1; }

    - name: Compile Coq Project
      run: |
        SWITCH_NAME="collatz-proof"

        echo "Activating environment for switch '${SWITCH_NAME}'..."
        eval $(opam env --switch="${SWITCH_NAME}" --set-switch)

        echo "Generating Makefile using coq_makefile..."
        coq_makefile -f _CoqProject -o Makefile || { echo "coq_makefile failed"; exit 1; }

        echo "Inspecting Makefile..."
        cat Makefile

        echo "Compiling Coq project using make..."
        make -j1 V=1 || { echo "Compilation failed, showing errors:"; cat *.v.err; exit 1; }
        echo "Compilation complete."